// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPricingHistory(arg1) {
  return window['go']['main']['App']['AddPricingHistory'](arg1);
}

export function AddSupplierToShortlist(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSupplierToShortlist'](arg1, arg2, arg3);
}

export function CreateCommunication(arg1) {
  return window['go']['main']['App']['CreateCommunication'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateCustomerContact(arg1) {
  return window['go']['main']['App']['CreateCustomerContact'](arg1);
}

export function CreateDocument(arg1) {
  return window['go']['main']['App']['CreateDocument'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function CreatePurchaseOrder(arg1, arg2) {
  return window['go']['main']['App']['CreatePurchaseOrder'](arg1, arg2);
}

export function CreateQuotation(arg1, arg2) {
  return window['go']['main']['App']['CreateQuotation'](arg1, arg2);
}

export function CreateSourcingRequest(arg1, arg2) {
  return window['go']['main']['App']['CreateSourcingRequest'](arg1, arg2);
}

export function CreateSupplier(arg1) {
  return window['go']['main']['App']['CreateSupplier'](arg1);
}

export function CreateSupplierContact(arg1) {
  return window['go']['main']['App']['CreateSupplierContact'](arg1);
}

export function CreateSupplierNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSupplierNote'](arg1, arg2, arg3);
}

export function CreateTender(arg1, arg2) {
  return window['go']['main']['App']['CreateTender'](arg1, arg2);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteCommunication(arg1) {
  return window['go']['main']['App']['DeleteCommunication'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteCustomerContact(arg1) {
  return window['go']['main']['App']['DeleteCustomerContact'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeletePurchaseOrder(arg1) {
  return window['go']['main']['App']['DeletePurchaseOrder'](arg1);
}

export function DeleteQuotation(arg1) {
  return window['go']['main']['App']['DeleteQuotation'](arg1);
}

export function DeleteSeedData() {
  return window['go']['main']['App']['DeleteSeedData']();
}

export function DeleteSourcingRequest(arg1) {
  return window['go']['main']['App']['DeleteSourcingRequest'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['main']['App']['DeleteSupplier'](arg1);
}

export function DeleteSupplierContact(arg1) {
  return window['go']['main']['App']['DeleteSupplierContact'](arg1);
}

export function DeleteTender(arg1) {
  return window['go']['main']['App']['DeleteTender'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function ExecuteImport(arg1) {
  return window['go']['main']['App']['ExecuteImport'](arg1);
}

export function ExportData(arg1) {
  return window['go']['main']['App']['ExportData'](arg1);
}

export function ExportDataXLSX(arg1) {
  return window['go']['main']['App']['ExportDataXLSX'](arg1);
}

export function ExportToCSV(arg1) {
  return window['go']['main']['App']['ExportToCSV'](arg1);
}

export function ExtractFromImage(arg1) {
  return window['go']['main']['App']['ExtractFromImage'](arg1);
}

export function GetActivityLog(arg1) {
  return window['go']['main']['App']['GetActivityLog'](arg1);
}

export function GetAllCommunications() {
  return window['go']['main']['App']['GetAllCommunications']();
}

export function GetCommunications(arg1, arg2) {
  return window['go']['main']['App']['GetCommunications'](arg1, arg2);
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetCurrentUserRole(arg1) {
  return window['go']['main']['App']['GetCurrentUserRole'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['main']['App']['GetCustomer'](arg1);
}

export function GetCustomerContacts(arg1) {
  return window['go']['main']['App']['GetCustomerContacts'](arg1);
}

export function GetCustomers(arg1) {
  return window['go']['main']['App']['GetCustomers'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDocuments() {
  return window['go']['main']['App']['GetDocuments']();
}

export function GetDocumentsByEntity(arg1, arg2) {
  return window['go']['main']['App']['GetDocumentsByEntity'](arg1, arg2);
}

export function GetExtractionConfig() {
  return window['go']['main']['App']['GetExtractionConfig']();
}

export function GetImportHistory(arg1) {
  return window['go']['main']['App']['GetImportHistory'](arg1);
}

export function GetImportTemplate(arg1) {
  return window['go']['main']['App']['GetImportTemplate'](arg1);
}

export function GetMonthlySpend() {
  return window['go']['main']['App']['GetMonthlySpend']();
}

export function GetOnTimeDeliveryRate() {
  return window['go']['main']['App']['GetOnTimeDeliveryRate']();
}

export function GetOrganization() {
  return window['go']['main']['App']['GetOrganization']();
}

export function GetPricingHistory(arg1) {
  return window['go']['main']['App']['GetPricingHistory'](arg1);
}

export function GetProduct(arg1) {
  return window['go']['main']['App']['GetProduct'](arg1);
}

export function GetProductSuppliers(arg1) {
  return window['go']['main']['App']['GetProductSuppliers'](arg1);
}

export function GetProducts(arg1) {
  return window['go']['main']['App']['GetProducts'](arg1);
}

export function GetPurchaseOrder(arg1) {
  return window['go']['main']['App']['GetPurchaseOrder'](arg1);
}

export function GetPurchaseOrderLineItems(arg1) {
  return window['go']['main']['App']['GetPurchaseOrderLineItems'](arg1);
}

export function GetPurchaseOrders(arg1, arg2) {
  return window['go']['main']['App']['GetPurchaseOrders'](arg1, arg2);
}

export function GetQuotation(arg1) {
  return window['go']['main']['App']['GetQuotation'](arg1);
}

export function GetQuotationComparison(arg1) {
  return window['go']['main']['App']['GetQuotationComparison'](arg1);
}

export function GetQuotationLineItems(arg1) {
  return window['go']['main']['App']['GetQuotationLineItems'](arg1);
}

export function GetQuotations(arg1, arg2) {
  return window['go']['main']['App']['GetQuotations'](arg1, arg2);
}

export function GetShortlistedSuppliers(arg1) {
  return window['go']['main']['App']['GetShortlistedSuppliers'](arg1);
}

export function GetSourcingRequest(arg1) {
  return window['go']['main']['App']['GetSourcingRequest'](arg1);
}

export function GetSourcingRequestProducts(arg1) {
  return window['go']['main']['App']['GetSourcingRequestProducts'](arg1);
}

export function GetSourcingRequestStats(arg1) {
  return window['go']['main']['App']['GetSourcingRequestStats'](arg1);
}

export function GetSourcingRequests(arg1, arg2) {
  return window['go']['main']['App']['GetSourcingRequests'](arg1, arg2);
}

export function GetSpendingBySupplier() {
  return window['go']['main']['App']['GetSpendingBySupplier']();
}

export function GetSupplier(arg1) {
  return window['go']['main']['App']['GetSupplier'](arg1);
}

export function GetSupplierContacts(arg1) {
  return window['go']['main']['App']['GetSupplierContacts'](arg1);
}

export function GetSupplierNotes(arg1) {
  return window['go']['main']['App']['GetSupplierNotes'](arg1);
}

export function GetSupplierProducts(arg1) {
  return window['go']['main']['App']['GetSupplierProducts'](arg1);
}

export function GetSuppliers(arg1) {
  return window['go']['main']['App']['GetSuppliers'](arg1);
}

export function GetTender(arg1) {
  return window['go']['main']['App']['GetTender'](arg1);
}

export function GetTenderItems(arg1) {
  return window['go']['main']['App']['GetTenderItems'](arg1);
}

export function GetTenderPerformance() {
  return window['go']['main']['App']['GetTenderPerformance']();
}

export function GetTenderSuppliers(arg1) {
  return window['go']['main']['App']['GetTenderSuppliers'](arg1);
}

export function GetTenders(arg1, arg2) {
  return window['go']['main']['App']['GetTenders'](arg1, arg2);
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GlobalSearch(arg1) {
  return window['go']['main']['App']['GlobalSearch'](arg1);
}

export function InviteSupplierToTender(arg1, arg2) {
  return window['go']['main']['App']['InviteSupplierToTender'](arg1, arg2);
}

export function LinkSupplierProduct(arg1) {
  return window['go']['main']['App']['LinkSupplierProduct'](arg1);
}

export function LogActivity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LogActivity'](arg1, arg2, arg3, arg4, arg5);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ParseFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ParseFile'](arg1, arg2, arg3);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function RemoveSupplierFromShortlist(arg1) {
  return window['go']['main']['App']['RemoveSupplierFromShortlist'](arg1);
}

export function RemoveSupplierFromTender(arg1) {
  return window['go']['main']['App']['RemoveSupplierFromTender'](arg1);
}

export function SaveExtractedData(arg1, arg2) {
  return window['go']['main']['App']['SaveExtractedData'](arg1, arg2);
}

export function SaveExtractionConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveExtractionConfig'](arg1, arg2, arg3);
}

export function SaveOrganization(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveOrganization'](arg1, arg2, arg3, arg4, arg5);
}

export function SeedDatabase() {
  return window['go']['main']['App']['SeedDatabase']();
}

export function UnlinkSupplierProduct(arg1) {
  return window['go']['main']['App']['UnlinkSupplierProduct'](arg1);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateProduct(arg1, arg2) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2);
}

export function UpdatePurchaseOrderStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdatePurchaseOrderStatus'](arg1, arg2);
}

export function UpdateQuotationStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuotationStatus'](arg1, arg2);
}

export function UpdateSourcingRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSourcingRequest'](arg1, arg2, arg3);
}

export function UpdateSourcingRequestStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateSourcingRequestStatus'](arg1, arg2);
}

export function UpdateSupplier(arg1, arg2) {
  return window['go']['main']['App']['UpdateSupplier'](arg1, arg2);
}

export function UpdateSupplierShortlistStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateSupplierShortlistStatus'](arg1, arg2);
}

export function UpdateTenderStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTenderStatus'](arg1, arg2);
}

export function UpdateTenderSupplierStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTenderSupplierStatus'](arg1, arg2);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateImport'](arg1, arg2, arg3);
}
