// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPricingHistory(arg1:main.PricingHistory):Promise<main.PricingHistory>;

export function AddSupplierToShortlist(arg1:number,arg2:number,arg3:string):Promise<number>;

export function CreateCommunication(arg1:main.Communication):Promise<number>;

export function CreateCustomer(arg1:main.Customer):Promise<number>;

export function CreateCustomerContact(arg1:main.CustomerContact):Promise<number>;

export function CreateDocument(arg1:main.Document):Promise<number>;

export function CreateProduct(arg1:main.Product):Promise<main.Product>;

export function CreatePurchaseOrder(arg1:main.PurchaseOrder,arg2:Array<main.PurchaseOrderLineItem>):Promise<number>;

export function CreateQuotation(arg1:main.Quotation,arg2:Array<main.QuotationLineItem>):Promise<number>;

export function CreateSourcingRequest(arg1:main.SourcingRequest,arg2:Array<main.SourcingRequestProduct>):Promise<number>;

export function CreateSupplier(arg1:main.Supplier):Promise<main.Supplier>;

export function CreateSupplierContact(arg1:main.SupplierContact):Promise<main.SupplierContact>;

export function CreateSupplierNote(arg1:number,arg2:string,arg3:any):Promise<main.SupplierNote>;

export function CreateTender(arg1:main.Tender,arg2:Array<main.TenderItem>):Promise<number>;

export function CreateUser(arg1:main.CreateUserRequest):Promise<main.User>;

export function DeleteCommunication(arg1:number):Promise<void>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function DeleteCustomerContact(arg1:number):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function DeletePurchaseOrder(arg1:number):Promise<void>;

export function DeleteQuotation(arg1:number):Promise<void>;

export function DeleteSeedData():Promise<void>;

export function DeleteSourcingRequest(arg1:number):Promise<void>;

export function DeleteSupplier(arg1:number):Promise<void>;

export function DeleteSupplierContact(arg1:number):Promise<void>;

export function DeleteTender(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function ExecuteImport(arg1:main.ImportExecuteRequest):Promise<main.ImportResult>;

export function ExportData(arg1:string):Promise<string>;

export function ExportDataXLSX(arg1:string):Promise<string>;

export function ExportToCSV(arg1:string):Promise<Array<number>>;

export function ExtractFromImage(arg1:main.ExtractionRequest):Promise<main.ExtractionResult>;

export function GetActivityLog(arg1:number):Promise<Array<main.ActivityLogEntry>>;

export function GetAllCommunications():Promise<Array<main.Communication>>;

export function GetCommunications(arg1:string,arg2:number):Promise<Array<main.Communication>>;

export function GetCurrentSession():Promise<main.User>;

export function GetCurrentUserRole(arg1:number):Promise<string>;

export function GetCustomer(arg1:number):Promise<main.Customer>;

export function GetCustomerContacts(arg1:number):Promise<Array<main.CustomerContact>>;

export function GetCustomers(arg1:string):Promise<Array<main.Customer>>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetDataDir():Promise<string>;

export function GetDocuments():Promise<Array<main.Document>>;

export function GetDocumentsByEntity(arg1:string,arg2:number):Promise<Array<main.Document>>;

export function GetExtractionConfig():Promise<main.ExtractionConfig>;

export function GetImportHistory(arg1:number):Promise<Array<main.ImportJob>>;

export function GetImportTemplate(arg1:string):Promise<main.ImportPreview>;

export function GetMonthlySpend():Promise<Array<main.MonthlySpend>>;

export function GetOnTimeDeliveryRate():Promise<Array<main.OnTimeDelivery>>;

export function GetOrganization():Promise<main.Organization>;

export function GetPricingHistory(arg1:number):Promise<Array<main.PricingHistory>>;

export function GetProduct(arg1:number):Promise<main.Product>;

export function GetProductSuppliers(arg1:number):Promise<Array<main.SupplierProduct>>;

export function GetProducts(arg1:string):Promise<Array<main.Product>>;

export function GetPurchaseOrder(arg1:number):Promise<main.PurchaseOrder>;

export function GetPurchaseOrderLineItems(arg1:number):Promise<Array<main.PurchaseOrderLineItem>>;

export function GetPurchaseOrders(arg1:string,arg2:string):Promise<Array<main.PurchaseOrder>>;

export function GetQuotation(arg1:number):Promise<main.Quotation>;

export function GetQuotationComparison(arg1:number):Promise<Array<main.QuotationComparisonRow>>;

export function GetQuotationLineItems(arg1:number):Promise<Array<main.QuotationLineItem>>;

export function GetQuotations(arg1:string,arg2:string):Promise<Array<main.Quotation>>;

export function GetShortlistedSuppliers(arg1:number):Promise<Array<main.SupplierShortlist>>;

export function GetSourcingRequest(arg1:number):Promise<main.SourcingRequest>;

export function GetSourcingRequestProducts(arg1:number):Promise<Array<main.SourcingRequestProduct>>;

export function GetSourcingRequestStats(arg1:number):Promise<Record<string, any>>;

export function GetSourcingRequests(arg1:string,arg2:string):Promise<Array<main.SourcingRequest>>;

export function GetSpendingBySupplier():Promise<Array<main.SpendingBySupplier>>;

export function GetSupplier(arg1:number):Promise<main.Supplier>;

export function GetSupplierContacts(arg1:number):Promise<Array<main.SupplierContact>>;

export function GetSupplierNotes(arg1:number):Promise<Array<main.SupplierNote>>;

export function GetSupplierProducts(arg1:number):Promise<Array<main.SupplierProduct>>;

export function GetSuppliers(arg1:string):Promise<Array<main.Supplier>>;

export function GetTender(arg1:number):Promise<main.Tender>;

export function GetTenderItems(arg1:number):Promise<Array<main.TenderItem>>;

export function GetTenderPerformance():Promise<Array<main.TenderPerformance>>;

export function GetTenderSuppliers(arg1:number):Promise<Array<main.TenderSupplier>>;

export function GetTenders(arg1:string,arg2:string):Promise<Array<main.Tender>>;

export function GetUser(arg1:number):Promise<main.User>;

export function GetUsers():Promise<Array<main.User>>;

export function GetVersion():Promise<string>;

export function GlobalSearch(arg1:string):Promise<Array<main.SearchResult>>;

export function InviteSupplierToTender(arg1:number,arg2:number):Promise<number>;

export function LinkSupplierProduct(arg1:main.SupplierProduct):Promise<main.SupplierProduct>;

export function LogActivity(arg1:any,arg2:string,arg3:string,arg4:any,arg5:string):Promise<void>;

export function Login(arg1:main.LoginRequest):Promise<main.LoginResponse>;

export function Logout():Promise<void>;

export function ParseFile(arg1:string,arg2:Array<number>,arg3:string):Promise<main.ImportPreview>;

export function Register(arg1:main.RegisterRequest):Promise<main.User>;

export function RemoveSupplierFromShortlist(arg1:number):Promise<void>;

export function RemoveSupplierFromTender(arg1:number):Promise<void>;

export function SaveExtractedData(arg1:string,arg2:Record<string, any>):Promise<number>;

export function SaveExtractionConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveOrganization(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Organization>;

export function SeedDatabase():Promise<void>;

export function UnlinkSupplierProduct(arg1:number):Promise<void>;

export function UpdateCustomer(arg1:number,arg2:main.Customer):Promise<void>;

export function UpdateProduct(arg1:number,arg2:main.Product):Promise<void>;

export function UpdatePurchaseOrderStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateQuotationStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateSourcingRequest(arg1:number,arg2:main.SourcingRequest,arg3:Array<main.SourcingRequestProduct>):Promise<void>;

export function UpdateSourcingRequestStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateSupplier(arg1:number,arg2:main.Supplier):Promise<void>;

export function UpdateSupplierShortlistStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateTenderStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateTenderSupplierStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ValidateImport(arg1:string,arg2:Array<main.ColumnMapping>,arg3:Array<any>):Promise<Array<main.ImportValidation>>;
